apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: namespace
    app.kubernetes.io/instance: system
    app.kubernetes.io/component: manager
    app.kubernetes.io/created-by: k8s-s3-operator
    app.kubernetes.io/part-of: k8s-s3-operator
    app.kubernetes.io/managed-by: kustomize
  name: system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: k8s-s3-operator-system
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: deployment
    app.kubernetes.io/instance: controller-manager
    app.kubernetes.io/component: manager
    app.kubernetes.io/created-by: k8s-s3-operator
    app.kubernetes.io/part-of: k8s-s3-operator
    app.kubernetes.io/managed-by: kustomize
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        control-plane: controller-manager
    spec:
      containers:
      - command:
        - /manager
        image: controller:local
        name: manager
        volumeMounts:
        - mountPath: /var/run/secrets/tokens
          name: token
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
        env:
        - name: AWS_SECRET_ACCESS_KEY
          value: test
        - name: AWS_ACCESS_KEY_ID
          value: test
        - name: DEVMODE
          value: "true"
      serviceAccountName: k8s-s3-operator-controller-manager
      volumes:
      - name: token
        projected:
          sources:
          - serviceAccountToken:
              path: token
              expirationSeconds: 7200
      terminationGracePeriodSeconds: 10
---
kind: ConfigMap 
apiVersion: v1 
metadata:
  name: config-map-body
  namespace: k8s-s3-operator-system 
data:
  # Configuration values can be set as key-value properties
  img: spec.Containers[0].Image
  serviceaccount: spec.serviceAccountName
