# permissions for end users to view s3buckets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: s3bucket-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: k8s-s3-operator
    app.kubernetes.io/part-of: k8s-s3-operator
    app.kubernetes.io/managed-by: kustomize
  name: s3bucket-viewer-role
rules:
- apiGroups:
  - s3operator.payu.com
  resources:
  - s3buckets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - s3operator.payu.com
  resources:
  - s3buckets/status
  verbs:
  - get
