apiVersion: s3operator.payu.com/v1
kind: S3Bucket
metadata:
  labels:
    app.kubernetes.io/name: s3bucket
    app.kubernetes.io/instance: s3bucket-sample
    app.kubernetes.io/part-of: k8s-s3-operator
    app.kuberentes.io/managed-by: kustomize
    app.kubernetes.io/created-by: k8s-s3-operator
  name: s3bucket-sample
  namespace: k8s-s3-operator-system
spec: